### ISSUE TITLE
WhiteScreen

### ISSUE THREAD

**Issue by ligi** [AkashaProject/dapp#214]
Just got a whitescreen with akasha:

![akasha_whitescreen](https://user-images.githubusercontent.com/111600/36486422-c08fb4e0-171e-11e8-925d-8ffacd202102.png)

looks like the UI froze - AFAIR after I clicked on the transactions log icon 
this is in the console:
```

mainApi: 74.639ms
total: 2030.084ms
contracts inited
uncaughtException Cannot read property 'args' of undefined TypeError: Cannot read property 'args' of undefined
    at tagCreateEvent.watch (/home/ligi/bin/akasha/resources/app.asar/main/modules/search/sync-tags.js:22:33)
    at /home/ligi/bin/akasha/resources/app.asar/node_modules/web3/lib/web3/filter.js:159:17
    at Array.forEach (native)
    at Object.callback (/home/ligi/bin/akasha/resources/app.asar/node_modules/web3/lib/web3/filter.js:158:28)
    at /home/ligi/bin/akasha/resources/app.asar/node_modules/web3/lib/web3/method.js:142:25
    at Object.<anonymous> (/home/ligi/bin/akasha/resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:86:20)
    at /home/ligi/bin/akasha/resources/app.asar/node_modules/@akashaproject/geth-connector/node_modules/web3/lib/web3/ipcprovider.js:66:44
    at Array.forEach (native)
    at Socket.<anonymous> (/home/ligi/bin/akasha/resources/app.asar/node_modules/@akashaproject/geth-connector/node_modules/web3/lib/web3/ipcprovider.js:50:47)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
Circuit { Strings: [ 'connect QmWfVX1MTacGQ1to1u17MtHPpgANR1UJk9h6JqtbYaRKre success' ] }                                                15:46:15
Circuit { Strings: [ 'connect QmTMSgsyw3zzVbcQnkoN5SRZk7WYUMorJ7EqkqVBLgn13i success' ] }
Circuit { Strings: [ 'connect QmTfTyKZXjzRo2C8NV6p21HCsxZF54Mm5cZ9GsfY3zpG3T success' ] }
Circuit { Strings: [ 'connect QmYfXRuVWMWFRJxUSFPHtScTNR9CU2samRsTK15VFJPpvh success' ] }
Circuit { Strings: [ 'connect QmUjM53zcSRhsA8BCK28DchCdSJCNmEU6W6jPJHiSgxwTW success' ] }
connect ipfs swarm circuit relay err  { Error: connect QmSgTsiHrubEkLKEvdEjNtWHRasU1dUSgPfMjJpkR8KkBU failure: dial attempt failed: <peer.ID NZew9L> --> <peer.ID SgTsiH> dial attempt failed: dial tcp4 10.19.0.6:4001: getsockopt: no route to host
    at parseError (/home/ligi/bin/akasha/resources/app.asar/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/home/ligi/bin/akasha/resources/app.asar/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20) code: 0 }
```

**Comment by kenshyx** [comment]
Which sync method did you use normal or light?

**Comment by ligi** [comment]
TBH I am not 100% sure anymore - I remember it asked me when setting up. But now I do not find it in the settings to check what I did choose at the time.I do not see it n app preferences or user settings.

![selection_231](https://user-images.githubusercontent.com/111600/36487307-da2a86f8-1720-11e8-85f6-7cee43b23eeb.png)
![selection_230](https://user-images.githubusercontent.com/111600/36487316-dcd244b8-1720-11e8-9767-1cc831018929.png)
![selection_229](https://user-images.githubusercontent.com/111600/36487320-df39bc54-1720-11e8-8b34-c385540ddbfb.png)

If I would guess I would say LES with p=0.85

**Comment by kenshyx** [comment]
There is a problem with contract events on LES :/. Can you try with a normal sync? Thanks!

**Comment by ligi** [comment]
where is the settings-file for this? Or is it somewhere in the UI and I am just too blind?

**Comment by kenshyx** [comment]
You're right we don't have an option for this to modify :man_facepalming: . You have to go to 'Help' -> Clear Cache and Reset App Data. After that restart the app and the first time setup options should be available

**Comment by ligi** [comment]
Thanks. Does `reset app data` clear my account? Is anything lost and not recoverable when the only thing I did to backup is `Backup keys?` Kind of already a little bit attached to the account ..) Btw. will we have to start from 0 when going Beta->Release?

**Comment by kenshyx** [comment]
Reset app data just clears all the local dbs from electron which contain logs and transaction history.
> will we have to start from 0 when going Beta->Release?
We will definitely archive and migrate good content from beta -> release

**Comment by SaiKarthik1911** [comment]
Even I got the same white screen when I clicked on the transaction log icon. I had to force quit Akasha and re-open it to get it back.
