### ISSUE TITLE
Fast restart after close goes belly up

### ISSUE THREAD

**Issue by karalabe** [AkashaProject/dapp#53]
If I close Akasha and try to start it back up fast (few seconds later), nothing happens. Looking at the console, there's a crash log:

```
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/akasha/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/opt/akasha/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/opt/akasha/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

```

**Comment by kenshyx** [comment]
This happens because when you close the app it doesn't exit immediately. It just hides the renderer browser window until all the services all closed(geth & ipfs) and after all these the main process can exit. This can take up to 5-6 seconds.

**Comment by karalabe** [comment]
I know why it happens, it just annoys me :D

**Comment by ligi** [comment]
Just had this error persist - see the timestamps: 

```
⋊> ~/b/akasha ./akasha                                                                                                                           13:55:53
Gtk-Message: 13:55:55.580: Failed to load module "canberra-gtk-module"
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/ligi/bin/akasha/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/ligi/bin/akasha/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/ligi/bin/akasha/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
⋊> ~/b/akasha [1;2A                                                                                                                              13:55:57
⋊> ~/b/akasha ./akasha                                                                                                                           13:57:19
Gtk-Message: 13:57:20.968: Failed to load module "canberra-gtk-module"
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/ligi/bin/akasha/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/ligi/bin/akasha/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/ligi/bin/akasha/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
⋊> ~/b/akasha ./akasha                                                                                                                           13:57:22
Gtk-Message: 13:57:53.855: Failed to load module "canberra-gtk-module"
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/ligi/bin/akasha/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/ligi/bin/akasha/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/ligi/bin/akasha/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
⋊> ~/b/akasha ./akasha                                                                                                                           14:10:27
Gtk-Message: 14:10:37.965: Failed to load module "canberra-gtk-module"
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/ligi/bin/akasha/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/ligi/bin/akasha/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/ligi/bin/akasha/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
⋊> ~/b/akasha ./akasha                                                                                                                           14:10:39
Gtk-Message: 14:17:41.937: Failed to load module "canberra-gtk-module"
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/ligi/bin/akasha/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/home/ligi/bin/akasha/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/home/ligi/bin/akasha/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

```
